services:
    app:
        build:
            context: ./docker/app
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ./docker/app/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        networks:
            - app-network
        depends_on:
            - mysql
        environment:
            MYSQL_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        tty: true

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - app
        networks:
            - app-network

    mysql:
        image: mysql:8
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:3306"
        networks:
            - app-network

    npm:
        image: node:latest
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        command: ["/bin/sh", "-c", "npm install && tail -f /dev/null"]
        ports:
            - "5173:5173"
        networks:
            - app-network
        depends_on:
            - app

    composer:
        image: composer:latest
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - app-network
        depends_on:
            - app

volumes:
    mysql-data:
        driver: local

networks:
    app-network:
        driver: bridge
